#!/usr/bin/python3
"""Module that factorize as many numbers into a product
of two numbers."""
from sys import argv

def factorize(number):
    """"print a descomposition of an integer greater than 1"""
    x = 2

    if number < 2:
        return
    while number % x:
        x += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number, number / x, x))

if len(argv) != 2:
    exit()

try:
    file_o = open(argv[1])
    with file_o as file:
        line = file.readline()

        while line != "":
            number = int(line.split('\n')[0])
            factorize(number)
            line = file.readline()
except:
    pass
